/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Discovered hardware key backend */
export interface HardwareKeyInfo {
  /** "yubikey-piv" or "secure-enclave" */
  backend: string
  /** Human-readable description */
  description: string
  /** Supported algorithms: "ES256", "RS256", etc. */
  algorithms: Array<string>
  /** For YubiKey: serial number. For Secure Enclave: "local" */
  deviceId: string
}
/** Result of key generation */
export interface GeneratedKey {
  /** Backend that holds the key */
  backend: string
  /** Key identifier (slot for PIV, tag for Secure Enclave) */
  keyId: string
  /** Algorithm used */
  algorithm: string
  /** Public key as JWK JSON string */
  publicJwk: string
}
/** Result of a signing operation */
export interface SignatureResult {
  /** Raw signature bytes (r||s for ECDSA, raw for RSA) */
  signature: Buffer
  /** Algorithm used */
  algorithm: string
}
/** Discover available hardware key backends */
export declare function discover(): Array<HardwareKeyInfo>
/** Generate a key on the specified backend */
export declare function generateKey(backend: string, algorithm: string): GeneratedKey
/**
 * Sign a hash with a hardware key
 * For JWT: pass the SHA-256 hash of the header.payload string
 */
export declare function signHash(backend: string, keyId: string, hash: Buffer): SignatureResult
/** List existing keys on a backend */
export declare function listKeys(backend: string): Array<GeneratedKey>
